STRINGS.NAMES.KJ = "Lined With Soft Armor"         
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KJ= "Be sure to protect yourself"  
STRINGS.RECIPE_DESC.KJ = "Pretty good soft armor" 


STRINGS.NAMES.FOREVERLIGHT = "Forever light"
STRINGS.RECIPE_DESC.FOREVERLIGHT = "Forever light"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOREVERLIGHT = "turn on at night!"