--铠甲
STRINGS.NAMES.KJ = "内衬软甲"         
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KJ= "一定要保护好自己呀"  
STRINGS.RECIPE_DESC.KJ = "相当强悍的软甲" 

STRINGS.NAMES.CHANGCHUNMAO = "牛牛帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHANGCHUNMAO = "可以升级的帽子"
STRINGS.RECIPE_DESC.CHANGCHUNMAO= "相当可以"
	
STRINGS.NAMES.FOREVERLIGHT = "永亮灯"
STRINGS.RECIPE_DESC.FOREVERLIGHT = "永亮灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOREVERLIGHT = "夜晚打开"